#
###################################
# Site wide configuration
####################################
#
title: Jiacheng Zhang
email: zhangjiachengwang@163.com
description: Jiacheng Zhang's blog,powered by jekyll.
url: https://zhangjiacheng.github.io 
keywords: ["Mobile", "Salesforce"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Changsha/China
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jiacheng Zhang
  avatar: avatar.jpg
  job: "Mobile Developer"
  bio: "A mobile developer who loves attemping everything. Working for Unisoft in Changsha, China."
  email: zhangjiachengwang@163.com
  disqus-shortname: #username
  twitter:  #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: zhangjiacheng #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
