# Basic
title: Jiacheng Zhang
subtitle: Personal Site
description: Welcome to my personal site
email: zhangjiachengwang@163.com
avatarTitle: Jiacheng
avatarDesc: Mobile Developer 
url: "https://zhangjiacheng.github.io"

# Comment
comment:
    disqus: jiacheng
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    weibo: 1111111 
    github: zhangjiacheng
    # twitter: 
    mail: zhangjiachengwang@163.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
#baidu:
#    id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
#    id: UA-84134159-3   
#    host: auto  



permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Posts

# Navigation buttons in the front page.s
#nav:
#    - {title: All posts, description: archive, url: "https://zhangjiacheng.github.io/archive" }   
#    - {title: Flag, description: tags, url: "https://zhangjiacheng.github.io/tags" }      
#    - {title: About me, description: about, url: "https://zhangjiacheng.github.io/about" }      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


